chain_width = 80
comment_width = 100
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Item"
max_width = 100
newline_style = "Unix"
normalize_doc_attributes = true
reorder_impl_items = true
reorder_imports = true
struct_field_align_threshold = 20
tab_spaces = 2
unstable_features = true
use_field_init_shorthand = false
use_try_shorthand = true
wrap_comments = true
